installStatePath: ./.yarn/install-state.gz

nodeLinker: pnp

# packageExtensions:
#   '@nrwl/next@*':
#     dependencies:
#       express: ^4.17.3

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32
yarnPath: .yarn/releases/yarn-3.2.4.cjs
